from enum import StrEnum


class EpisodeStatus(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    ABANDONED = "ABANDONED"


class PropositionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    RETRACTED = "RETRACTED"


class FactStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    RETRACTED = "RETRACTED"


class HypothesisStatus(StrEnum):
    PLAUSIBLE = "PLAUSIBLE"
    SUPPORTED = "SUPPORTED"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"


class GapStatus(StrEnum):
    OPEN = "OPEN"
    FOCUSED = "FOCUSED"
    RESOLVED = "RESOLVED"
    INVALIDATED = "INVALIDATED"


class EvidenceRelation(StrEnum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    RESOLVES = "RESOLVES"
    NEUTRAL = "NEUTRAL"


class CognitiveTargetType(StrEnum):
    FACT = "FACT"
    HYPOTHESIS = "HYPOTHESIS"
    GAP = "GAP"


class ActionKind(StrEnum):
    TOOL = "TOOL"
    ASK_USER = "ASK_USER"
    RESPOND = "RESPOND"


class ActionRisk(StrEnum):
    READ_ONLY = "READ_ONLY"
    WRITE_LOCAL = "WRITE_LOCAL"
    WRITE_EXTERNAL = "WRITE_EXTERNAL"
    DESTRUCTIVE = "DESTRUCTIVE"


class ActionResultStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


class TurnResolutionKind(StrEnum):
    RESPOND = "RESPOND"
    ACT = "ACT"
    ASK = "ASK"
    BLOCKED = "BLOCKED"
    COMPLETE = "COMPLETE"


class EventType(StrEnum):
    EPISODE_CREATED = "EPISODE_CREATED"
    GOAL_CONTRACT_CREATED = "GOAL_CONTRACT_CREATED"
    GOAL_CONTRACT_REVISED = "GOAL_CONTRACT_REVISED"
    OBSERVATION_ADDED = "OBSERVATION_ADDED"
    PROPOSITION_ADDED = "PROPOSITION_ADDED"
    EVIDENCE_LINK_ADMITTED = "EVIDENCE_LINK_ADMITTED"
    FACT_ADDED = "FACT_ADDED"
    FACT_SUPERSEDED = "FACT_SUPERSEDED"
    FACT_RETRACTED = "FACT_RETRACTED"
    HYPOTHESIS_CREATED = "HYPOTHESIS_CREATED"
    HYPOTHESIS_STATUS_CHANGED = "HYPOTHESIS_STATUS_CHANGED"
    GAP_OPENED = "GAP_OPENED"
    GAP_FOCUSED = "GAP_FOCUSED"
    GAP_RESOLVED = "GAP_RESOLVED"
    ACTION_DECIDED = "ACTION_DECIDED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    EPISODE_COMPLETED = "EPISODE_COMPLETED"


class ChangeKind(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"


class CognitiveObjectType(StrEnum):
    OBSERVATION = "OBSERVATION"
    PROPOSITION = "PROPOSITION"
    FACT = "FACT"
    HYPOTHESIS = "HYPOTHESIS"
    INFORMATION_GAP = "INFORMATION_GAP"
    ACTION = "ACTION"

