from enum import StrEnum


class EpisodeStatus(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    ABANDONED = "ABANDONED"


class PropositionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    RETRACTED = "RETRACTED"


class FactStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    RETRACTED = "RETRACTED"


class FactBasis(StrEnum):
    SOURCE_REPORT = "SOURCE_REPORT"
    ARTIFACT_CONTENT = "ARTIFACT_CONTENT"
    DIRECT_MEASUREMENT = "DIRECT_MEASUREMENT"
    DETERMINISTIC_DERIVATION = "DETERMINISTIC_DERIVATION"


class SemanticEntailment(StrEnum):
    EQUIVALENT_OR_NARROWER = "EQUIVALENT_OR_NARROWER"
    STRONGER_THAN_SOURCE = "STRONGER_THAN_SOURCE"
    AMBIGUOUS = "AMBIGUOUS"


class FactAdmissionDecision(StrEnum):
    ADMIT = "ADMIT"
    DEFER = "DEFER"
    REJECT = "REJECT"


class AdmissionDecision(StrEnum):
    ADMIT = "ADMIT"
    DEFER = "DEFER"
    REJECT = "REJECT"
    NO_NEW_ADMISSION = "NO_NEW_ADMISSION"


class AdmissionReasonCode(StrEnum):
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    TARGET_NOT_FOUND = "TARGET_NOT_FOUND"
    EPISODE_MISMATCH = "EPISODE_MISMATCH"
    TARGET_TYPE_MISMATCH = "TARGET_TYPE_MISMATCH"
    RELATION_NOT_ALLOWED = "RELATION_NOT_ALLOWED"
    NEUTRAL_EVIDENCE = "NEUTRAL_EVIDENCE"
    DUPLICATE_EVIDENCE = "DUPLICATE_EVIDENCE"
    RELATION_CONFLICT = "RELATION_CONFLICT"
    PROPOSITION_INACTIVE = "PROPOSITION_INACTIVE"
    CLAIM_TOO_STRONG = "CLAIM_TOO_STRONG"
    SCOPE_EXPANDED = "SCOPE_EXPANDED"
    TEMPORAL_SCOPE_INVALID = "TEMPORAL_SCOPE_INVALID"
    SOURCE_FITNESS_INSUFFICIENT = "SOURCE_FITNESS_INSUFFICIENT"
    SEMANTIC_AMBIGUITY = "SEMANTIC_AMBIGUITY"
    NON_EXPLANATORY_BOUNDARY = "NON_EXPLANATORY_BOUNDARY"
    NO_SUPPORTING_PROPOSITION = "NO_SUPPORTING_PROPOSITION"
    NO_SUPPORTING_EVIDENCE = "NO_SUPPORTING_EVIDENCE"
    MISSING_TESTABLE_EXPECTATION = "MISSING_TESTABLE_EXPECTATION"
    FACT_CONFLICT = "FACT_CONFLICT"
    MISSING_DRAFT_OBJECT = "MISSING_DRAFT_OBJECT"
    EVIDENCE_REFERENCE_INVALID = "EVIDENCE_REFERENCE_INVALID"
    CONFLICTING_OBJECT_CHANGES = "CONFLICTING_OBJECT_CHANGES"
    INVALID_INITIAL_STATUS = "INVALID_INITIAL_STATUS"
    COGNITIVE_STRUCTURE_INVALID = "COGNITIVE_STRUCTURE_INVALID"


class HypothesisStatus(StrEnum):
    PLAUSIBLE = "PLAUSIBLE"
    SUPPORTED = "SUPPORTED"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"


class GapStatus(StrEnum):
    OPEN = "OPEN"
    FOCUSED = "FOCUSED"
    RESOLVED = "RESOLVED"
    INVALIDATED = "INVALIDATED"


class EvidenceRelation(StrEnum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    RESOLVES = "RESOLVES"
    NEUTRAL = "NEUTRAL"


class CognitiveTargetType(StrEnum):
    FACT = "FACT"
    HYPOTHESIS = "HYPOTHESIS"
    GAP = "GAP"


class ActionKind(StrEnum):
    TOOL = "TOOL"
    ASK_USER = "ASK_USER"
    RESPOND = "RESPOND"


class ActionRisk(StrEnum):
    READ_ONLY = "READ_ONLY"
    WRITE_LOCAL = "WRITE_LOCAL"
    WRITE_EXTERNAL = "WRITE_EXTERNAL"
    DESTRUCTIVE = "DESTRUCTIVE"


class ActionResultStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


class TurnResolutionKind(StrEnum):
    RESPOND = "RESPOND"
    ACT = "ACT"
    ASK = "ASK"
    BLOCKED = "BLOCKED"
    COMPLETE = "COMPLETE"


class EventType(StrEnum):
    EPISODE_CREATED = "EPISODE_CREATED"
    GOAL_CONTRACT_CREATED = "GOAL_CONTRACT_CREATED"
    GOAL_CONTRACT_REVISED = "GOAL_CONTRACT_REVISED"
    OBSERVATION_ADDED = "OBSERVATION_ADDED"
    PROPOSITION_ADDED = "PROPOSITION_ADDED"
    EVIDENCE_LINK_ADMITTED = "EVIDENCE_LINK_ADMITTED"
    FACT_ADDED = "FACT_ADDED"
    FACT_SUPERSEDED = "FACT_SUPERSEDED"
    FACT_RETRACTED = "FACT_RETRACTED"
    HYPOTHESIS_CREATED = "HYPOTHESIS_CREATED"
    HYPOTHESIS_STATUS_CHANGED = "HYPOTHESIS_STATUS_CHANGED"
    GAP_OPENED = "GAP_OPENED"
    GAP_FOCUSED = "GAP_FOCUSED"
    GAP_RESOLVED = "GAP_RESOLVED"
    ACTION_DECIDED = "ACTION_DECIDED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    EPISODE_COMPLETED = "EPISODE_COMPLETED"


class ChangeKind(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"


class CognitiveObjectType(StrEnum):
    OBSERVATION = "OBSERVATION"
    PROPOSITION = "PROPOSITION"
    FACT = "FACT"
    HYPOTHESIS = "HYPOTHESIS"
    INFORMATION_GAP = "INFORMATION_GAP"
    ACTION = "ACTION"

